import os
import json
import glob
from pathlib import Path
from osgeo import gdal
from hyp3_autorift import geometry, utils
from hyp3_autorift.vend.testGeogrid import GeogridOptical, runGeogrid
from hyp3_autorift.vend.testautoRIFT import generateAutoriftProduct

# Create dummy class to hold metadata
class Dummy(object):
    pass

def process_event(manifest_path):
    # Read the manifest generated by coseis.py
    with open(manifest_path, 'r') as f:
        manifest = json.load(f)
        
    if manifest.get("status") != "DOWNLOADED_READY_FOR_AUTORIFT":
        print(f"Skipping {manifest.get('event_title')} - Status is {manifest.get('status')}")
        return

    title = manifest["event_title"]
    ref_path = manifest["pre_composite_path"]
    sec_path = manifest["post_composite_path"]
    
    print(f"\n{'='*50}")
    print(f"Starting autoRIFT processing for: {title}")
    print(f"{'='*50}")
    
    # Change working directory to the event folder to store outputs
    event_dir = os.path.dirname(manifest_path)
    original_dir = os.getcwd()
    os.chdir(event_dir)
    
    try:
        local_ref = os.path.basename(ref_path)
        local_sec = os.path.basename(sec_path)
        
        parameter_file = '/vsicurl/https://its-live-data.s3.amazonaws.com/autorift_parameters/v001/autorift_solidearth_0120m.shp'

        print("Calculating bounding box from local image...")
        info_json = gdal.Info(local_ref, format='json')
        coords = info_json['wgs84Extent']['coordinates'][0]
        lons = [c[0] for c in coords]
        lats = [c[1] for c in coords]
        poly = geometry.polygon_from_bbox(x_limits=(min(lats), max(lats)), y_limits=(min(lons), max(lons)))

        print("Fetching regional parameters from S3 Shapefile...")
        parameter_info = utils.find_jpl_parameter_info(poly, parameter_file)

        print("Manually co-registering to avoid filename parsing...")
        obj = GeogridOptical()
        x1a, y1a, xsize1, ysize1, x2a, y2a, xsize2, ysize2, trans = obj.coregister(local_ref, local_sec)

        # Inject dummy metadata
        info_m = Dummy()
        info_m.startingX = trans[0]
        info_m.startingY = trans[3]
        info_m.XSize = trans[1]
        info_m.YSize = trans[5]
        info_m.numberOfLines = ysize1
        info_m.numberOfSamples = xsize1
        info_m.filename = local_ref
        info_m.time = "20190101"  # Dummy date

        info_s = Dummy()
        info_s.time = "20190102"  # Dummy date

        print("Running Geogrid...")
        geogrid_info = runGeogrid(info_m, info_s, epsg=parameter_info['epsg'], optical_flag=1, **parameter_info['geogrid'])

        print("Running autoRIFT...")
        gdal.AllRegister()

        try:
            generateAutoriftProduct(
                local_ref,
                local_sec,
                nc_sensor="DUMMY_SENSOR", 
                optical_flag=True,
                ncname=None,
                geogrid_run_info=geogrid_info,
                **parameter_info['autorift'],
                parameter_file=parameter_file.replace('/vsicurl/', '')
            )
        except Exception as e:
            if "netCDF packaging not supported" in str(e):
                print("Successfully completed autoRIFT (skipped NetCDF packaging).")
            else:
                raise e

        # Rename the hardcoded outputs to match the event
        print("Renaming output files for data provenance...")
        out_prefix = f"{title}_autorift"
        
        if os.path.exists("velocity.tif"):
            os.rename("velocity.tif", f"{out_prefix}_velocity.tif")
        if os.path.exists("offset.tif"):
            os.rename("offset.tif", f"{out_prefix}_offset.tif")

        # Update the manifest to show processing is complete
        manifest["status"] = "PROCESSED_AUTORIFT_COMPLETE"
        with open(os.path.basename(manifest_path), 'w') as f:
            json.dump(manifest, f, indent=4)
            
        print(f"Finished {title}. Outputs saved in {event_dir}")

    finally:
        # ALWAYS revert back to the root directory so the next loop iteration works
        os.chdir(original_dir)

def main():
    # Gets the absolute path to the project root (one level up from /scripts)
    root_dir = Path(__file__).resolve().parent.parent 
    
    # Search for all manifest files in the GEE_Optical_Downloads directory
    search_pattern = root_dir / "data" / "GEE_Optical_Downloads" / "**" / "*_autorift_manifest.json"
    manifest_files = glob.glob(str(search_pattern), recursive=True)
    
    if not manifest_files:
        print("No manifest files found. Ensure coseis.py has downloaded the composites.")
        return
        
    for manifest_path in manifest_files:
        process_event(manifest_path)

if __name__ == "__main__":
    main()